/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.AbstractJasperReports;
import clases.FileManager;
import clases.Mensajes;
import clases.Utilities;
import clases.coordinates;
import com.google.gson.Gson;
import dataBase.DB;
import dto.DtoPrestamo;
import entidades.Pago;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import reportes.pago.ReportePago;

import reportes.pago.ticket_pago;

/**
 *
 * @author JuanLuis
 */
public class frm_insert_pago extends javax.swing.JDialog {

    /**
     * Creates new form frm_insert_pago
     */
    public frm_insert_pago() {
        initComponents();
        txt_id.setText(Integer.toString(Utilities.getMaxId("pago")));
        DatePicker.setEnabled(false);
        coordinates point = Utilities.getCenterLocation(this);
        this.setLocation(point.getX(), point.getY());
        
    }
    
    public frm_insert_pago(java.awt.Dialog parent,boolean modal){
        super(parent,modal);
        initComponents();
        txt_id.setText(Integer.toString(Utilities.getMaxId("pago")));
        DatePicker.setEnabled(false);
        coordinates point = Utilities.getCenterLocation(this);
        this.setLocation(point.getX(), point.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        sqlDateModel1 = new org.jdatepicker.impl.SqlDateModel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_limpiar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id_prestamo = new javax.swing.JTextField();
        rad_fecha_actual = new javax.swing.JRadioButton();
        rad_fecha_manual = new javax.swing.JRadioButton();
        cmb_tpago = new javax.swing.JComboBox();
        DatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ENTRADA PAGO");
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        txt_id.setBackground(new java.awt.Color(255, 255, 51));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.setEnabled(false);
        txt_id.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id.setName("txt_id"); // NOI18N
        txt_id.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id.setSelectionColor(new java.awt.Color(0, 255, 0));

        btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_limpiar.setName("btn_limpiar"); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_aceptar.setName("btn_aceptar"); // NOI18N
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TIPO DE PAGO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID DE PRESTAMO:");

        txt_id_prestamo.setBackground(new java.awt.Color(255, 255, 51));
        txt_id_prestamo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id_prestamo.setEnabled(false);
        txt_id_prestamo.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id_prestamo.setName("txt_id"); // NOI18N
        txt_id_prestamo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id_prestamo.setSelectionColor(new java.awt.Color(0, 255, 0));

        buttonGroup1.add(rad_fecha_actual);
        rad_fecha_actual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_fecha_actual.setSelected(true);
        rad_fecha_actual.setText("FECHA ACTUAL");
        rad_fecha_actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_fecha_actualActionPerformed(evt);
            }
        });

        buttonGroup1.add(rad_fecha_manual);
        rad_fecha_manual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rad_fecha_manual.setText("FECHA MANUAL");
        rad_fecha_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_fecha_manualActionPerformed(evt);
            }
        });

        cmb_tpago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDIENTE", "MORA", "PAPELEO" }));
        cmb_tpago.setAutoscrolls(true);
        cmb_tpago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tpagoItemStateChanged(evt);
            }
        });
        cmb_tpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tpagoActionPerformed(evt);
            }
        });

        DatePicker.setBackground(new java.awt.Color(255, 255, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CANTIDAD RD$:");

        txt_cantidad.setBackground(new java.awt.Color(255, 255, 51));
        txt_cantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cantidad.setEnabled(false);
        txt_cantidad.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_cantidad.setName("txt_id"); // NOI18N
        txt_cantidad.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_cantidad.setSelectionColor(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aceptar)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar)
                .addGap(18, 18, 18)
                .addComponent(btn_limpiar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(txt_id_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cantidad)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_tpago, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad_fecha_actual)
                    .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rad_fecha_manual))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rad_fecha_actual)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rad_fecha_manual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txt_id_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_tpago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rad_fecha_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_fecha_manualActionPerformed
        // TODO add your handling code here:
        DatePicker.setEnabled(true);
    }//GEN-LAST:event_rad_fecha_manualActionPerformed

    private void rad_fecha_actualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_fecha_actualActionPerformed
        // TODO add your handling code here:
        DatePicker.setEnabled(false);
    }//GEN-LAST:event_rad_fecha_actualActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        if(cmb_tpago.getItemCount()==4)
            cmb_tpago.removeItemAt(3);
                    
        frm_consult_prestamo frm = new frm_consult_prestamo(this,true);
        frm.setVisible(true);
        
        if(DtoPrestamo.getIdPrestamo()!=0){
            txt_id_prestamo.setText(Integer.toString(DtoPrestamo.getIdPrestamo()));
            DB dbase = Utilities.getConection();
            String sql = "select cliente_id from prestamo where id = "+DtoPrestamo.getIdPrestamo()+"";
            String sql2 = "select forma_prestamo_id from tipo_prestamo where id = "+DtoPrestamo.getPrestamo().getTipo_prestamo_id()+"";
            Utilities.println(sql2);
            try {
                ResultSet rs = dbase.execSelect(sql);
                rs.next();
                dto.DtoCliente.setIdCliente(rs.getInt(1));
                
                rs = dbase.execSelect(sql2);
                rs.next();
                int forma_pago = rs.getInt(1);
                if(forma_pago == 2){
                    String[] items = {"PENDIENTE","MORA","PAPELEO","FINAL"};
                    
                    
                    cmb_tpago.addItem(items[3]);
                    
                  
                }
                
               
                
            } catch (SQLException ex) {
                Logger.getLogger(frm_insert_pago.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(!txt_id_prestamo.getText().equals("")){
            int index = cmb_tpago.getSelectedIndex();
            int idTipo_prest = DtoPrestamo.getPrestamo().getTipo_prestamo_id();
            txt_cantidad.setText(Float.toString(Utilities.getPago(index, idTipo_prest)));
        }
        
    }//GEN-LAST:event_jLabel4MousePressed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        
        //String network_path_printer="\\\\10.0.0.36\\tickeadora";
        //ticket_pago report=new ticket_pago(network_path_printer, true);    

        
        
        
        if(Utilities.txtVoid(getContentPane())==false){
            Mensajes.mensajeError(evt, "Todos los Campos son Obligatorios");
            return;   
        }
        else
        {  
            //if(report.test_stream()) {
                Pago pago = new Pago();
                pago.setId(Integer.parseInt(txt_id.getText()));
                pago.setId_tipo_pago(cmb_tpago.getSelectedIndex()+1);
                pago.setId_prestamo(Integer.parseInt(txt_id_prestamo.getText()));
                if(rad_fecha_actual.isSelected())
                    pago.setFecha((Date) Utilities.getCurrentDate());
                if(rad_fecha_manual.isSelected()){
                    int day = DatePicker.getDate().getDate();
                    int month = DatePicker.getDate().getMonth();
                    int Year = DatePicker.getDate().getYear();
                    Date date = new Date(Year, month, day);
                    pago.setFecha(date);
                }
            
                Gson json = new Gson();
                String respon = pago.insertar_pago(json.toJson(pago));
            
                if(respon.equals("1")){
                    try {
                        Mensajes.mensajeInfo(evt, "SE AGREGO CON EXITO");
                        btn_aceptar.setEnabled(false);
                        ReportePago ds = new ReportePago(pago.getId());
                        String report = "/reportes/pago/pagoReport.jasper";
                        InputStream reportIS = this.getClass()
                                .getResourceAsStream(report);
                        AbstractJasperReports jasper = new AbstractJasperReports(ds, reportIS,null);
                        jasper.showViewer();
                        //report.print(Integer.parseInt(txt_id.getText()));
                        this.setVisible(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(frm_insert_pago.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (JRException ex) {
                        Logger.getLogger(frm_insert_pago.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(respon.equals("0"))
                    Mensajes.mensajeError(evt, "EL CLIETE YA HA SALDADO EL PRESTAMO");   
                else if(respon.equals("-1"))
                    Mensajes.mensajeError(evt, "ERROR DE INSERCION");  
                else if(respon.equals("2"))
                    Mensajes.mensajeError(evt, "EL PAPELEO YA HA SIDO PAGADO");  
                else
                    Mensajes.mensajeError(evt, "ERROR DE BASE DE DATOS"); 
            
            
            /*} 
            else
            {
                ActionEvent evt2 = new ActionEvent(this, 50, "Error de impresion");
                Mensajes.mensajeError(evt2, "No se encuentra la impresora, usted puede\nInspeccionar el estado de la impresora\nY el estado de la red ");
            }*/
        }
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formFocusGained

    private void cmb_tpagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tpagoItemStateChanged
        // TODO add your handling code here:
        if(!txt_id_prestamo.getText().isEmpty()){
            int index = cmb_tpago.getSelectedIndex();
            int idTipo_prest = DtoPrestamo.getPrestamo().getTipo_prestamo_id();
            txt_cantidad.setText(Float.toString(Utilities.getPago(index, idTipo_prest)));
        }
    }//GEN-LAST:event_cmb_tpagoItemStateChanged

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        Utilities.txtClean(getContentPane());
        txt_id.setText(Integer.toString(Utilities.getMaxId("pago")));
        DatePicker.setEnabled(false);
        DatePicker.setDate(null);
        rad_fecha_actual.setSelected(true);
        btn_aceptar.setEnabled(true);
        
        
               
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void cmb_tpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tpagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_insert_pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_insert_pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_insert_pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_insert_pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_insert_pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatePicker;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cmb_tpago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rad_fecha_actual;
    private javax.swing.JRadioButton rad_fecha_manual;
    private org.jdatepicker.impl.SqlDateModel sqlDateModel1;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id_prestamo;
    // End of variables declaration//GEN-END:variables
}
