/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.Mensajes;
import clases.Tiempo;
import clases.Utilities;
import clases.coordinates;
import com.google.gson.Gson;
import dto.DtoRuta;
import entidades.Ruta;
import java.sql.Time;

/**
 *
 * @author JuanLuis
 */
public class frm_insert_ruta extends javax.swing.JDialog {

    /**
     * Creates new form frm_insert_ruta
     */
    int eleccion = 0;
    public frm_insert_ruta (java.awt.Frame parent,boolean modal){
        super(parent,modal);
        initComponents();
        txt_id.setText(Integer.toString(Utilities.getMaxId("ruta")));
        cmb_estado.setEnabled(false);
        coordinates point = Utilities.getCenterLocation(this);
        this.setLocation(point.getX(), point.getY());
    }
    
    public frm_insert_ruta (java.awt.Dialog parent,boolean modal){
        super(parent,modal);
        eleccion =1;
        initComponents();
        
        txt_id.setText(Integer.toString(DtoRuta.getRuta().getId()));
        cmb_dia.setSelectedItem(DtoRuta.getRuta().getDia());//Este metodo esta a prueba por mi
            Time hora_inicial = DtoRuta.getRuta().getHora_entrada();
            Time hora_final = DtoRuta.getRuta().getHora_salida();
            /*************Adaptador tiempo para los combo box******************/
            Tiempo time_inicial = Tiempo.adaptadorTiempo(hora_inicial);
            Tiempo time_final = Tiempo.adaptadorTiempo(hora_final);
        cmb_hora_entrada.setSelectedIndex(time_inicial.getHora());
        cmb_minuto_entrada.setSelectedIndex(time_inicial.getMinuto());
        cmb_meridiano_entrada.setSelectedIndex(time_inicial.getMeridiano());
        
        cmb_hora_salida.setSelectedIndex(time_final.getHora());
        cmb_minuto_salida.setSelectedIndex(time_final.getMinuto());
        cmb_meridiano_salida.setSelectedIndex(time_final.getMeridiano());
        
        txt_id_usuario.setText(Integer.toString(DtoRuta.getRuta().getIdUsuario()));
        cmb_estado.setEnabled(true);
        coordinates point = Utilities.getCenterLocation(this);
        this.setLocation(point.getX(), point.getY());
    }
    
    public frm_insert_ruta() {
        initComponents();
        Utilities.getMaxId("ruta");
        coordinates point = Utilities.getCenterLocation(this);
        this.setLocation(point.getX(), point.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        cmb_dia = new javax.swing.JComboBox();
        cmb_hora_entrada = new javax.swing.JComboBox();
        cmb_meridiano_entrada = new javax.swing.JComboBox();
        cmb_meridiano_salida = new javax.swing.JComboBox();
        cmb_hora_salida = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_descripcion = new javax.swing.JTextArea();
        cmb_minuto_entrada = new javax.swing.JComboBox();
        cmb_minuto_salida = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmb_estado = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txt_id_usuario = new javax.swing.JTextField();
        lbl_buscar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ENTRADA RUTA");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("HORA FINAL");

        txt_id.setBackground(new java.awt.Color(255, 255, 51));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.setEnabled(false);
        txt_id.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id.setName("txt_id"); // NOI18N
        txt_id.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id.setSelectionColor(new java.awt.Color(0, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DIA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("HORA INICIAL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID ");

        btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpiar.setName("btn_limpiar"); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_aceptar.setName("btn_aceptar"); // NOI18N
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        cmb_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO" }));
        cmb_dia.setAutoscrolls(true);

        cmb_hora_entrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmb_hora_entrada.setAutoscrolls(true);

        cmb_meridiano_entrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        cmb_meridiano_entrada.setAutoscrolls(true);

        cmb_meridiano_salida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        cmb_meridiano_salida.setAutoscrolls(true);

        cmb_hora_salida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmb_hora_salida.setAutoscrolls(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DESCRIPCION");

        txtA_descripcion.setBackground(new java.awt.Color(255, 255, 0));
        txtA_descripcion.setColumns(20);
        txtA_descripcion.setLineWrap(true);
        txtA_descripcion.setRows(5);
        jScrollPane1.setViewportView(txtA_descripcion);

        cmb_minuto_entrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "15", "30", "45" }));
        cmb_minuto_entrada.setAutoscrolls(true);

        cmb_minuto_salida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "15", "30", "45" }));
        cmb_minuto_salida.setAutoscrolls(true);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ESTADO");

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVO", "INACTIVO\t" }));
        cmb_estado.setAutoscrolls(true);
        cmb_estado.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("USUARIO");

        txt_id_usuario.setBackground(new java.awt.Color(255, 255, 51));
        txt_id_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id_usuario.setEnabled(false);
        txt_id_usuario.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id_usuario.setName("txt_id_usuario"); // NOI18N
        txt_id_usuario.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id_usuario.setSelectionColor(new java.awt.Color(0, 255, 0));

        lbl_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        lbl_buscar.setToolTipText("");
        lbl_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_buscarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 207, Short.MAX_VALUE)
                        .addComponent(btn_aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmb_dia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cmb_hora_salida, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmb_hora_entrada, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmb_minuto_entrada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmb_minuto_salida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmb_meridiano_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_meridiano_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_buscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmb_hora_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_meridiano_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_minuto_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_meridiano_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_hora_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_minuto_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_buscar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        if(Utilities.txtVoid(getContentPane())==false){
            Mensajes.mensajeError(evt, "Todos los Campos son Obligatorios");
        }
        else{
            
            Tiempo hora_entrada=new Tiempo(cmb_hora_entrada.getSelectedIndex()+1, cmb_minuto_entrada.getSelectedIndex(), cmb_meridiano_entrada.getSelectedIndex());
            Tiempo hora_salida= new Tiempo(cmb_hora_salida.getSelectedIndex()+1,cmb_minuto_salida.getSelectedIndex(),cmb_meridiano_salida.getSelectedIndex());
            Ruta ruta = new Ruta();
            ruta.setId(Integer.parseInt(txt_id.getText()));
            ruta.setDia((String)cmb_dia.getSelectedItem());
            ruta.setHora_entrada(hora_entrada.getTiempo());
            ruta.setHora_salida(hora_salida.getTiempo());
            ruta.setDescripcion(txtA_descripcion.getText());
            ruta.setIdUsuario(Integer.parseInt(txt_id_usuario.getText()));
            
            Gson json = new Gson();
            if(eleccion == 0){
                ruta.setEstado(0);
                String respon = ruta.insertar_ruta(json.toJson(ruta));
                if(respon.equals("02000")){
                    Mensajes.mensajeInfo(evt, "SE INSERTO CORRECTAMENTE");
                    Utilities.setDisable(getContentPane());
                    
                    txtA_descripcion.setEnabled(false);
                    this.dispose();
                }
                else
                    Mensajes.mensajeError(evt, "Error de la base de datos");
                    System.out.println(respon);
            }
            else{
                ruta.setEstado(cmb_estado.getSelectedIndex());
                String respon = ruta.modificar_ruta(json.toJson(ruta));
                if(respon.equals("02000")){
                    Mensajes.mensajeInfo(evt, "SE MODIFICO CORRECTAMENTE");
                    Utilities.setDisable(getContentPane());
                    txtA_descripcion.setEnabled(false);
                    this.dispose();
                }
                else
                    Mensajes.mensajeError(evt, "Error de la base de datos");
            }
            
            
            
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        if(Mensajes.confirmar(evt, "desea salir")==0){
           
           this.dispose();
          
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        Utilities.txtClean(getContentPane());
        Utilities.setEnable(getContentPane());
        
        txtA_descripcion.setText("");
        txtA_descripcion.setEnabled(true);
        txt_id.setText(Integer.toString(Utilities.getMaxId("ruta")));
        txt_id.setEnabled(true);
        
        
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void lbl_buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscarMousePressed
        // TODO add your handling code here:
        frm_consult_user frm = new frm_consult_user(this, true);
        frm.setVisible(true);
        txt_id_usuario.setText(Integer.toString(dto.DtoUsuario.getId_user()));
        
    }//GEN-LAST:event_lbl_buscarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_insert_ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_insert_ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_insert_ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_insert_ruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_insert_ruta dialog = new frm_insert_ruta(new javax.swing.JFrame(),true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JComboBox cmb_dia;
    private javax.swing.JComboBox cmb_estado;
    private javax.swing.JComboBox cmb_hora_entrada;
    private javax.swing.JComboBox cmb_hora_salida;
    private javax.swing.JComboBox cmb_meridiano_entrada;
    private javax.swing.JComboBox cmb_meridiano_salida;
    private javax.swing.JComboBox cmb_minuto_entrada;
    private javax.swing.JComboBox cmb_minuto_salida;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JTextArea txtA_descripcion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id_usuario;
    // End of variables declaration//GEN-END:variables
}
