/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import clases.AbstractJasperReports;
import clases.Mensajes;
import clases.Utilities;
import clases.coordinates;
import com.google.gson.Gson;
import dto.DtoCliente;
import dto.DtoPrestamo;
import dto.DtoRuta;
import dto.DtoTPrestamo;
import dto.DtoUsuario;
import entidades.Cliente;
import entidades.Prestamo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import reportes.recibo_prestamo.reportePrestamo;



/**
 *
 * @author JuanLuis
 */
public class frm_insert_prestamo extends javax.swing.JDialog {

    /**
     * Creates new form frm_insert_prestamo
     */
    int eleccion=1;
    int cantFocus;
   
    public frm_insert_prestamo() {
        initComponents();
        txt_id.setEnabled(false);
        txt_id.setText(Integer.toString(Utilities.getMaxId("prestamo")));
        eleccion=0;
        coordinates point = Utilities.getCenterLocation(this);
        this.setLocation(point.getX(), point.getY());
    }

    public frm_insert_prestamo(java.awt.Frame parent , boolean modal) {
        super(parent,modal);
        eleccion=0;
        initComponents();
        //Contrucctor de inserciones
        txt_id.setEnabled(false);
        txt_id.setText(Integer.toString(Utilities.getMaxId("prestamo")));
        coordinates point = Utilities.getCenterLocation(this);
        this.setLocation(point.getX(), point.getY());
        
    }
    
    public frm_insert_prestamo(java.awt.Dialog parent , boolean modal) {
        super(parent,modal);
        eleccion = 1;//*****opcion que maneja el flujo

        initComponents();
        //Contrucctor de modificaciones
        btn_aceptar.setText("MODIFICAR");
        txt_id.setEnabled(false);
        btn_limpiar.setEnabled(false);
        txt_id.setText(Integer.toString(DtoPrestamo.getPrestamo().getId()));
        txt_id.setEnabled(false);
        txt_id_cliente.setText(Integer.toString(DtoPrestamo.getPrestamo().getCliente_id()));
        txt_id_cliente.setEnabled(false);
        lbl_buscar_idCliente.setVisible(false);
        
        txt_id_tprestamo.setText(Integer.toString(DtoPrestamo.getPrestamo().getTipo_prestamo_id()));
        txt_id_tprestamo.setEnabled(false);
        lbl_buscar_tPrestamo.setVisible(false);
       
        
        txt_id_ruta.setText(Integer.toString(DtoPrestamo.getPrestamo().getRuta_id()));
        DtoPrestamo.setId_rutaSeleccionada(DtoPrestamo.getPrestamo().getRuta_id());
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        txt_id_tprestamo = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_id_ruta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_id_cliente = new javax.swing.JTextField();
        lbl_buscar_tPrestamo = new javax.swing.JLabel();
        lbl_buscar_idCliente = new javax.swing.JLabel();
        lbl_buscar_idRuta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ENTRADA PRESTAMO");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID CLIENTE:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID RUTA");

        btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_limpiar.setName("btn_limpiar"); // NOI18N

        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        btn_aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_aceptar.setName("btn_aceptar"); // NOI18N
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        txt_id_tprestamo.setBackground(new java.awt.Color(255, 255, 51));
        txt_id_tprestamo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id_tprestamo.setEnabled(false);
        txt_id_tprestamo.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id_tprestamo.setName("txt_id"); // NOI18N
        txt_id_tprestamo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id_tprestamo.setSelectionColor(new java.awt.Color(0, 255, 0));

        txt_id.setBackground(new java.awt.Color(255, 255, 51));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.setEnabled(false);
        txt_id.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id.setName("txt_id"); // NOI18N
        txt_id.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id.setSelectionColor(new java.awt.Color(0, 255, 0));

        txt_id_ruta.setBackground(new java.awt.Color(255, 255, 51));
        txt_id_ruta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id_ruta.setEnabled(false);
        txt_id_ruta.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id_ruta.setName("txt_id"); // NOI18N
        txt_id_ruta.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id_ruta.setSelectionColor(new java.awt.Color(0, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID TIPO PRESTAMO:");

        txt_id_cliente.setBackground(new java.awt.Color(255, 255, 51));
        txt_id_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id_cliente.setEnabled(false);
        txt_id_cliente.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id_cliente.setName("txt_id"); // NOI18N
        txt_id_cliente.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id_cliente.setSelectionColor(new java.awt.Color(0, 255, 0));

        lbl_buscar_tPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        lbl_buscar_tPrestamo.setToolTipText("");
        lbl_buscar_tPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_buscar_tPrestamoMousePressed(evt);
            }
        });

        lbl_buscar_idCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        lbl_buscar_idCliente.setToolTipText("");
        lbl_buscar_idCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_buscar_idClienteMousePressed(evt);
            }
        });

        lbl_buscar_idRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        lbl_buscar_idRuta.setToolTipText("");
        lbl_buscar_idRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_buscar_idRutaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(txt_id_tprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_buscar_tPrestamo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(txt_id_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_buscar_idRuta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_buscar_idCliente)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_buscar_tPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_id_tprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_buscar_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_id_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_buscar_idRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        /*if(eleccion == 0){
            System.out.print("Entro en 0");
            txt_id_cliente.setText(Integer.toString(DtoCliente.getIdCliente()));
            txt_id_tprestamo.setText(Integer.toString(DtoTPrestamo.getIdTPrestamo()));
            txt_id_ruta.setText(Integer.toString(DtoRuta.getIdRuta()));
            
            
        }
        else if(eleccion == 1){
            cantFocus++;
            System.out.print("Entro en 1");
            if(cantFocus == 1)
                txt_id_ruta.setText(Integer.toString(DtoPrestamo.getPrestamo().getRuta_id()));
            else
                txt_id_ruta.setText(Integer.toString(DtoPrestamo.getId_rutaSeleccionada()));
        }*/
    }//GEN-LAST:event_formWindowGainedFocus

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        if(Utilities.txtVoid(getContentPane())==false){
            Mensajes.mensajeError(evt, "Todos los Campos son Obligatorios");
        }
        else{
            Gson json = new Gson();
            Prestamo prestamo = new Prestamo();
            prestamo.setId(Integer.parseInt(txt_id.getText()));
            prestamo.setTipo_prestamo_id(Integer.parseInt(txt_id_tprestamo.getText()));
            prestamo.setCliente_id(Integer.parseInt(txt_id_cliente.getText()));
            prestamo.setRuta_id(Integer.parseInt(txt_id_ruta.getText()));
            
            prestamo.setUser(DtoUsuario.getUser().getId());
            
                if(eleccion == 0){
                    String respon = prestamo.insertar_Prestamo(json.toJson(prestamo));
                    if(respon.equals("1")){
                        Mensajes.mensajeInfo(evt, "SE AGREGO CON EXITO");
                        
                        /*String  path = "reportes\\prestamo\\prestamoReport.jasper";
                        reportePrestamo datasource = new reportePrestamo(Integer.parseInt(txt_id.getText()), Integer.parseInt(txt_id_cliente.getText()));
                        AbstractJasperReports.createReport(datasource, path);
                        AbstractJasperReports.showViewer();*/
                    }
                    
                    else if(respon.equals("2"))
                        Mensajes.mensajeError(evt,"NO HAY SUFICIENTE DINERO EN LA CUENTA PARA CREAR ESTE PRESTAMO");
                    else if(respon.equals("-1"))
                        Mensajes.mensajeError(evt,"Error en la funcion de insertar");
                    else
                        Mensajes.mensajeError(evt,"ERROR DE BASE DE DATOS");
                }
                else{
                    String respon = prestamo.modificar_ruta_cliente(json.toJson(prestamo));
                    if(respon.equals("02000")){
                        Mensajes.mensajeInfo(evt, "SE MODIFICO CORRECTAMENTE");
                    }
                    else
                        System.out.println("Error en la base de datos"+respon);
                }
            this.dispose();//Cierra el formulario
        }
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void lbl_buscar_tPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscar_tPrestamoMousePressed
        // TODO add your handling code here:
        frm_consult_tprestamo frm = new frm_consult_tprestamo(this,true);
        frm.setVisible(true);
        txt_id_tprestamo.setText(Integer.toString(DtoTPrestamo.getIdTPrestamo()));
    }//GEN-LAST:event_lbl_buscar_tPrestamoMousePressed

    private void lbl_buscar_idClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscar_idClienteMousePressed
        // TODO add your handling code here:
        frm_consult_client frm_cli = new frm_consult_client(this,true);
        frm_cli.setVisible(true);
        txt_id_cliente.setText(Integer.toString(DtoCliente.getIdCliente()));
    }//GEN-LAST:event_lbl_buscar_idClienteMousePressed

    private void lbl_buscar_idRutaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscar_idRutaMousePressed
        // TODO add your handling code here:
        frm_consult_ruta frm = new frm_consult_ruta(this, true);
        frm.setVisible(true);
        txt_id_ruta.setText(Integer.toString(DtoRuta.getIdRuta()));
    }//GEN-LAST:event_lbl_buscar_idRutaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_insert_prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_insert_prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_insert_prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_insert_prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_insert_prestamo dialog  = new frm_insert_prestamo(new javax.swing.JFrame(),true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_buscar_idCliente;
    private javax.swing.JLabel lbl_buscar_idRuta;
    private javax.swing.JLabel lbl_buscar_tPrestamo;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id_cliente;
    private javax.swing.JTextField txt_id_ruta;
    private javax.swing.JTextField txt_id_tprestamo;
    // End of variables declaration//GEN-END:variables
}
