/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.AbstractJasperReports;
import clases.Mensajes;
import clases.Respuesta;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import dto.DtoCliente;
import dto.DtoPago;
import dto.DtoPrestamo;
import entidades.Cliente;
import entidades.Pago;
import entidades.Ruta;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.io.InputStream;
import java.sql.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import reportes.ganancia.ReporteGananciaSource;

/**
 *
 * @author JuanLuis
 */
public class frm_consult_ganancia_detallada extends javax.swing.JDialog {

    /**
     * Creates new form frm_consult_pago
     */
    
    Date fecha_inicial,fecha_final;
    ArrayList<Pago> lista;
    public frm_consult_ganancia_detallada() {
        initComponents();
        GraphicsDevice grafica=GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        //grafica.setFullScreenWindow(this);
        this.setBounds(grafica.getDefaultConfiguration().getBounds());
        btn_imprimir.setEnabled(false);
        this.setVisible(true);
        
    }
    
    public frm_consult_ganancia_detallada(java.awt.Dialog parent,boolean modal){
        super(parent,modal);
        initComponents();
        GraphicsDevice grafica=GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        //grafica.setFullScreenWindow(this);
        this.setBounds(grafica.getDefaultConfiguration().getBounds());
        btn_imprimir.setEnabled(false);
        this.setVisible(true);
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        pago_table = new javax.swing.JTable();
        btn_buscar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_id_cliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton_final = new javax.swing.JRadioButton();
        jRadioButton_inicial = new javax.swing.JRadioButton();
        txt_fecha_inicial = new javax.swing.JTextField();
        txt_fecha_final = new javax.swing.JTextField();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        btn_limpiar_fecha = new javax.swing.JButton();
        btn_elegir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BUSCAR PAGOS Y GANANCIA");
        setResizable(false);

        pago_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pago_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pago_tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(pago_table);

        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_buscar.setName("btn_buscar"); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("CANCELAR");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setName("btn_aceptar"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID PRESTAMO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID CLIENTE:");

        txt_id.setBackground(new java.awt.Color(255, 255, 51));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id.setName("txt_id"); // NOI18N
        txt_id.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id.setSelectionColor(new java.awt.Color(0, 255, 0));
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });

        txt_id_cliente.setBackground(new java.awt.Color(255, 255, 51));
        txt_id_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id_cliente.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id_cliente.setName("txt_id_cliente"); // NOI18N
        txt_id_cliente.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id_cliente.setSelectionColor(new java.awt.Color(0, 255, 0));
        txt_id_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_id_clienteKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jRadioButton_final);
        jRadioButton_final.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton_final.setText("FECHA FINAL");
        jRadioButton_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_finalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_inicial);
        jRadioButton_inicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton_inicial.setSelected(true);
        jRadioButton_inicial.setText("FECHA INICIAL");

        txt_fecha_inicial.setBackground(new java.awt.Color(255, 255, 51));
        txt_fecha_inicial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_fecha_inicial.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_fecha_inicial.setName("txt_id"); // NOI18N
        txt_fecha_inicial.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_fecha_inicial.setSelectionColor(new java.awt.Color(0, 255, 0));

        txt_fecha_final.setBackground(new java.awt.Color(255, 255, 51));
        txt_fecha_final.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_fecha_final.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_fecha_final.setName("txt_id"); // NOI18N
        txt_fecha_final.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_fecha_final.setSelectionColor(new java.awt.Color(0, 255, 0));

        btn_limpiar_fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_limpiar_fecha.setText("LIMPIAR ");
        btn_limpiar_fecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_limpiar_fecha.setName("btn_aceptar"); // NOI18N
        btn_limpiar_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_fechaActionPerformed(evt);
            }
        });

        btn_elegir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_elegir.setText("ELEGIR FECHA");
        btn_elegir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_elegir.setName("btn_aceptar"); // NOI18N
        btn_elegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton_inicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_fecha_inicial)
                    .addComponent(jRadioButton_final)
                    .addComponent(txt_fecha_final))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_limpiar_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_elegir))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_elegir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_limpiar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jRadioButton_inicial)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_fecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton_final)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("BUSCAR PAGOS POR MEDIO DE:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("BUSCAR POR FECHA:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        jLabel8.setToolTipText("");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        btn_imprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_imprimir.setText("IMPRIMIR");
        btn_imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_imprimir.setName("btn_buscar"); // NOI18N
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(34, 34, 34)
                                        .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 394, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_imprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pago_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pago_tableMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_pago_tableMousePressed

    public boolean fechaIsEmpy(){
        if(txt_fecha_inicial.getText().isEmpty() || txt_fecha_final.getText().isEmpty())
            return true;
        else
            return false;     
    }
    
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        Gson json = new Gson();
        lista = new ArrayList<Pago>(); 
        DefaultTableModel modelo = new DefaultTableModel();
        String [] col = {"ID","FECHA","PAGO","MONTO PREST","INTERES PREST","GANANCIA PREST","# PAGOS PREST","MONTO PAGO","GANANCIA PAGO","GANANCIA ACUM"};
        Pago pago = new Pago();
        
        if(!txt_id.getText().isEmpty()){
        
            String informacion;
            Respuesta respon=null;
            
        
            if(fechaIsEmpy()){
                informacion = pago.consultar_pago(Integer.parseInt(txt_id.getText()));
                respon = json.fromJson(informacion,Respuesta.class);
            }
            else{
                informacion = pago.consultar_pago(Integer.parseInt(txt_id.getText()),fecha_inicial,fecha_final);
                respon = json.fromJson(informacion,Respuesta.class);
            }
            
            if(respon.getId()>0){
                JsonElement son = new JsonParser().parse(respon.getMensaje());
                JsonArray array = son.getAsJsonArray();
            
                for (JsonElement json2: array)
                {
                    pago = json.fromJson(json2,Pago.class);
                    lista.add(pago);
                }
            
                for (int i=0;i<col.length;i++)
                    modelo.addColumn(col[i]);
            
                int k;
                for(Pago p:lista){
                    
                           
                        k=0;
                        Object [] fila = new Object[10];
                        fila[k++]=(Object)p.getId();
                        fila[k++]=(Object)p.getFecha();
                        fila[k++]=(Object)p.getTipo_pago_nombre();
                        fila[k++]=(Object)p.getMonto_prestamo();
                        fila[k++]=(Object)p.getInteres_prestamo();
                        if(p.getGanancia_prestamo()==-3.0){
                             fila[k++] = (Object)"INDEFINIDO";
                        }
                        else{
                            fila[k++]=(Object)p.getGanancia_prestamo();
                        }
                        fila[k++]=(Object)p.getCantidad_pago_prestamo();
                        fila[k++]=(Object)p.getMonto_pago();
                        fila[k++]=(Object)p.getGanancia_pago();
                        fila[k++]=(Object)p.getGanancia_acumulada();

                        modelo.addRow(fila);
                    
                }
            
                pago_table.setModel(modelo);
            }
            else if(respon.getId()==0){
            
                Mensajes.mensajeError(evt,"NO SE ENCOTRARON RESULTADOS");
            }
            else{
                Mensajes.mensajeError(evt,"Error de la base de datos");
                System.out.println("Error bdd :"+respon.getMensaje());
            }
        }
        else if(!txt_id_cliente.getText().isEmpty()){
            String informacion;
            Respuesta respon=null;
            if(fechaIsEmpy()){
                informacion = pago.consultar_pago(txt_id_cliente.getText());
                respon = json.fromJson(informacion,Respuesta.class);
            }
            else{
                informacion = pago.consultar_pago(txt_id_cliente.getText(),fecha_inicial,fecha_final);
                respon = json.fromJson(informacion,Respuesta.class);
            }
            
            if(respon.getId()>0){
                JsonElement son = new JsonParser().parse(respon.getMensaje());
                JsonArray array = son.getAsJsonArray();
            
                for (JsonElement json2: array)
                {
                    pago = json.fromJson(json2,Pago.class);
                    lista.add(pago);
                }
            
                for (int i=0;i<col.length;i++)
                    modelo.addColumn(col[i]);
            
                int k;
                for(Pago p:lista){
                    k=0;
                        Object [] fila = new Object[10];
                        fila[k++]=(Object)p.getId();
                        fila[k++]=(Object)p.getFecha();
                        fila[k++]=(Object)p.getTipo_pago_nombre();
                        fila[k++]=(Object)p.getMonto_prestamo();
                        fila[k++]=(Object)p.getInteres_prestamo();
                        if(p.getGanancia_prestamo()==-3.0){
                             fila[k++] = (Object)"INDEFINIDO";
                        }
                        else{
                            fila[k++]=(Object)p.getGanancia_prestamo();
                        }
                        fila[k++]=(Object)p.getCantidad_pago_prestamo();
                        fila[k++]=(Object)p.getMonto_pago();
                        fila[k++]=(Object)p.getGanancia_pago();
                        fila[k++]=(Object)p.getGanancia_acumulada();
                        
                        modelo.addRow(fila);
                }
            
                pago_table.setModel(modelo);
            }
            else if(respon.getId()==0){
            
                Mensajes.mensajeError(evt,"No se encontraron resultados");
            }
            else{
                Mensajes.mensajeError(evt,"Error de la base de datos");
                System.out.println("Error bdd :"+respon.getMensaje());
            }
        }
        if(txt_id.getText().isEmpty() && txt_id_cliente.getText().isEmpty()){
            String informacion;
            Respuesta respon;
            
            if(fechaIsEmpy()){
                informacion = pago.consultar_pago();
                respon = json.fromJson(informacion,Respuesta.class);
            }
            else{
                informacion = pago.consultar_pago(fecha_inicial,fecha_final);
                respon = json.fromJson(informacion,Respuesta.class);
            }
            
            if(respon.getId()>0){
                JsonElement son = new JsonParser().parse(respon.getMensaje());
                JsonArray array = son.getAsJsonArray();
            
                for (JsonElement json2: array)
                {
                    pago = json.fromJson(json2,Pago.class);
                    lista.add(pago);
                }
            
                for (int i=0;i<col.length;i++)
                    modelo.addColumn(col[i]);
            
                int k;
                for(Pago p:lista){
                    k=0;
                        Object [] fila = new Object[10];
                        fila[k++]=(Object)p.getId();
                        fila[k++]=(Object)p.getFecha();
                        fila[k++]=(Object)p.getTipo_pago_nombre();
                        fila[k++]=(Object)p.getMonto_prestamo();
                        fila[k++]=(Object)p.getInteres_prestamo();
                        if(p.getGanancia_prestamo()==-3.0){
                             fila[k++] = (Object)"INDEFINIDO";
                        }
                        else{
                            fila[k++]=(Object)p.getGanancia_prestamo();
                        }
                        fila[k++]=(Object)p.getCantidad_pago_prestamo();
                        fila[k++]=(Object)p.getMonto_pago();
                        fila[k++]=(Object)p.getGanancia_pago();
                        fila[k++]=(Object)p.getGanancia_acumulada();
                
                        modelo.addRow(fila);
                }
            
                pago_table.setModel(modelo);
            }
            else if(respon.getId()==0){
            
                Mensajes.mensajeError(evt,"No se encontraron resultados");
            }
            else{
                Mensajes.mensajeError(evt,"Error de la base de datos");
                System.out.println("Error bdd :"+respon.getMensaje());
            }
        }
        btn_imprimir.setEnabled(true);
            

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_id_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_clienteKeyTyped
        // TODO add your handling code here:
        txt_id.setText("");
    }//GEN-LAST:event_txt_id_clienteKeyTyped

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        // TODO add your handling code here:
        txt_id_cliente.setText("");
    }//GEN-LAST:event_txt_idKeyTyped

    private void btn_elegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elegirActionPerformed
        // TODO add your handling code here:

        int day = jCalendar1.getDayChooser().getDay();
        int month = jCalendar1.getMonthChooser().getMonth();
        int year = jCalendar1.getYearChooser().getYear();
        if(jRadioButton_inicial.isSelected()){
            fecha_inicial = new Date(year, month, day);
            txt_fecha_inicial.setText(""+fecha_inicial.getDate()+"-"+(fecha_inicial.getMonth()+1)+"-"+fecha_inicial.getYear()+"");

        }
        else{
            fecha_final = new Date(year, month, day);
            txt_fecha_final.setText(""+fecha_final.getDate()+"-"+(fecha_final.getMonth()+1)+"-"+fecha_final.getYear()+"");
        }
    }//GEN-LAST:event_btn_elegirActionPerformed

    private void btn_limpiar_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_fechaActionPerformed
        // TODO add your handling code here:
        txt_fecha_inicial.setText("");
        txt_fecha_final.setText("");
    }//GEN-LAST:event_btn_limpiar_fechaActionPerformed

    private void jRadioButton_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_finalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_finalActionPerformed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
       DtoPrestamo.setIdPrestamo(-1);
       frm_consult_prestamo frm = new frm_consult_prestamo(this, true);
       frm.setVisible(true);
       txt_id.setText(Integer.toString(DtoPrestamo.getIdPrestamo()));
       

    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        DtoCliente.setIdCliente(-1);
        frm_consult_client frm = new frm_consult_client(this,true);
        frm.setVisible(true);
        txt_id_cliente.setText(Integer.toString(DtoCliente.getIdCliente()));
    }//GEN-LAST:event_jLabel8MousePressed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
        ReporteGananciaSource ganSource = new ReporteGananciaSource(lista);
        InputStream path = this.getClass().getResourceAsStream("/reportes/ganancia/gananciaReport.jasper");
        HashMap params = new HashMap();
        if(!txt_id.getText().isEmpty()){
            if(fechaIsEmpy()){
                params.put("origin", "PRESTAMO # "+txt_id.getText());
            }
            else{
                params.put("origin", "PRESTAMO # "+txt_id.getText()+" ENTRE "+txt_fecha_inicial.getText()+" Y "+txt_fecha_final.getText());
            }
        }
        else if(!txt_id_cliente.getText().isEmpty()){
            if(fechaIsEmpy()){
                params.put("origin", "CLIENTE # "+txt_id_cliente.getText());
            }
            else{
                params.put("origin", "CLIENTE # "+txt_id_cliente.getText()+" ENTRE "+txt_fecha_inicial.getText()+" Y "+txt_fecha_final.getText());
            }
        }
        else if(txt_id.getText().isEmpty() && txt_id_cliente.getText().isEmpty()){
            if(fechaIsEmpy()){
                params.put("origin", "DESDE EL INICIO DE LOS TIEMPOS");
            }
            else{
                params.put("origin", "ENTRE "+txt_fecha_inicial.getText()+" Y "+txt_fecha_final.getText());
            }
        }
       
        try {
            AbstractJasperReports jasper = new AbstractJasperReports(ganSource, path, params);
            jasper.showViewer();
        } catch (JRException ex) {
            Logger.getLogger(frm_consult_ganancia_detallada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_consult_ganancia_detallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_consult_ganancia_detallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_consult_ganancia_detallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_consult_ganancia_detallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_consult_ganancia_detallada();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_elegir;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_limpiar_fecha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_final;
    private javax.swing.JRadioButton jRadioButton_inicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pago_table;
    private javax.swing.JTextField txt_fecha_final;
    private javax.swing.JTextField txt_fecha_inicial;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id_cliente;
    // End of variables declaration//GEN-END:variables
}
