/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.Mensajes;
import clases.Utilities;
import clases.coordinates;
import dto.DtoPrestamo;
import entidades.Abono;

/**
 *
 * @author JuanLHT
 */
public class frm_consult_abono extends javax.swing.JDialog {

    /**
     * Creates new form frm_consult_abono
     */
    public frm_consult_abono() {
        initComponents();
    }
    public frm_consult_abono(java.awt.Frame parent,boolean modal){
        super(parent,modal);
        initComponents();
        
        coordinates point = Utilities.getCenterLocation(this);
        this.setLocation(point.getX(), point.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt_id_prestamo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_ret_monto = new javax.swing.JTextField();
        btn_retirar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID DE PRESTAMO:");

        txt_id_prestamo.setBackground(new java.awt.Color(255, 255, 51));
        txt_id_prestamo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id_prestamo.setEnabled(false);
        txt_id_prestamo.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_id_prestamo.setName("txt_id"); // NOI18N
        txt_id_prestamo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_id_prestamo.setSelectionColor(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MONTO:");

        txt_monto.setBackground(new java.awt.Color(255, 255, 51));
        txt_monto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_monto.setEnabled(false);
        txt_monto.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_monto.setName("txt_monto"); // NOI18N
        txt_monto.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_monto.setSelectionColor(new java.awt.Color(0, 255, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancelar.setText("SALIR");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("RETIRAR MONTO");

        txt_ret_monto.setBackground(new java.awt.Color(255, 255, 51));
        txt_ret_monto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ret_monto.setEnabled(false);
        txt_ret_monto.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_ret_monto.setName("txt_monto"); // NOI18N
        txt_ret_monto.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_ret_monto.setSelectionColor(new java.awt.Color(0, 255, 0));
        txt_ret_monto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ret_montoFocusGained(evt);
            }
        });
        txt_ret_monto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ret_montoMouseClicked(evt);
            }
        });
        txt_ret_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ret_montoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ret_montoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(txt_ret_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ret_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btn_retirar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_retirar.setText("RETIRAR");
        btn_retirar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(txt_id_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_retirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txt_id_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        

        frm_consult_prestamo frm = new frm_consult_prestamo(this,true);
        frm.setVisible(true);

        if(DtoPrestamo.getIdPrestamo()>0){
           txt_id_prestamo.setText(Integer.toString(DtoPrestamo.getIdPrestamo()));
           txt_monto.setText(Integer.toString(Abono.getMonto_Abono(DtoPrestamo.getIdPrestamo())));
           txt_ret_monto.setEnabled(true);
        }
        

    }//GEN-LAST:event_jLabel4MousePressed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retirarActionPerformed
        // TODO add your handling code here:
        int monto_retirar = Integer.parseInt(txt_ret_monto.getText());
        int monto_abono = Abono.getMonto_Abono(DtoPrestamo.getIdPrestamo());
        if(monto_retirar>monto_abono){
            Mensajes.mensajeError(evt, "NO ES POSIBLE RETIRAR ESTA CANTIDAD DE DINERO");
        }
        else
        {
            Abono.useAbono(DtoPrestamo.getIdPrestamo(), monto_retirar);
            Mensajes.mensajeInfo(evt, "SE RETIRO CORRECTAMENTE");
            btn_retirar.setEnabled(false);
            txt_ret_monto.setText("");
            txt_monto.setText(Integer.toString(Abono.getMonto_Abono(DtoPrestamo.getIdPrestamo())));
           
        }
    }//GEN-LAST:event_btn_retirarActionPerformed

    private void txt_ret_montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ret_montoKeyTyped
        // TODO add your handling code here:
        char caract=evt.getKeyChar();
        int code = caract;
        if(code<48 || code>57) {
                
                getToolkit().beep();
                evt.consume();
                
         }
        
    }//GEN-LAST:event_txt_ret_montoKeyTyped

    private void txt_ret_montoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ret_montoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_ret_montoKeyPressed

    private void txt_ret_montoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ret_montoFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txt_ret_montoFocusGained

    private void txt_ret_montoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ret_montoMouseClicked
        // TODO add your handling code here:
          btn_retirar.setEnabled(true);
    }//GEN-LAST:event_txt_ret_montoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_consult_abono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_consult_abono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_consult_abono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_consult_abono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_consult_abono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_retirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_id_prestamo;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_ret_monto;
    // End of variables declaration//GEN-END:variables
}
