/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.AbstractJasperReports;
import clases.Mensajes;
import clases.Utilities;
import dataBase.Backup;
import dto.DtoUsuario;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.jar.JarFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import reportes.prestamo_activo.PrestActRunnable;
import reportes.prestamo_activo.reportePrestamoActivo;

/**
 *
 * @author JuanLuis
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        GraphicsDevice grafica=GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
       
        this.setBounds(grafica.getDefaultConfiguration().getBounds());
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icono_AyM.png"));
        setIconImage(icon);
        
        
        if(DtoUsuario.getUser().getLeave()==0 || DtoUsuario.getUser().getLeave()==20)
        {
            jMenu_principal.setEnabled(true);
            jMenu_buscar.setEnabled(true);
            jMenu_nuevo.setEnabled(true);
            
        }
        else {
            jMenu_principal.setEnabled(false);
            jMenu_buscar.setEnabled(true);
            jMenu_nuevo.setEnabled(true);
            insUsuario.setEnabled(false);
        }
        
        
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_principal = new javax.swing.JMenu();
        menu_cuenta = new javax.swing.JMenuItem();
        menu_cuenta2 = new javax.swing.JMenuItem();
        menu_cuenta3 = new javax.swing.JMenuItem();
        jMenu_buscar = new javax.swing.JMenu();
        bscUsuario = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        bscPrestamo = new javax.swing.JMenuItem();
        bscTPrestamo = new javax.swing.JMenuItem();
        bscRuta = new javax.swing.JMenuItem();
        bscRuta1 = new javax.swing.JMenuItem();
        bscRuta2 = new javax.swing.JMenuItem();
        jMenu_nuevo = new javax.swing.JMenu();
        insUsuario = new javax.swing.JMenuItem();
        insPrestamo = new javax.swing.JMenuItem();
        insRuta = new javax.swing.JMenuItem();
        insRuta1 = new javax.swing.JMenuItem();
        insTPrestamo = new javax.swing.JMenuItem();
        insPago = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        insAbono = new javax.swing.JMenuItem();
        insPago1 = new javax.swing.JMenuItem();
        jMenu_config1 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        showReportPrestamosActivos = new javax.swing.JMenuItem();
        showReportPrestamosActivos1 = new javax.swing.JMenuItem();
        showReportPrestamosActivos2 = new javax.swing.JMenuItem();
        showReportPrestamosActivos3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem5.setText("jMenuItem5");

        jMenu6.setText("jMenu6");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVERSIONES A&M 2.5");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(8);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo_A&M.png"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuBar1.setInheritsPopupMenu(true);

        jMenu_principal.setText("principal");
        jMenu_principal.setFocusable(false);
        jMenu_principal.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        menu_cuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_cuenta.setText("Estado de Cuentas");
        menu_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cuentaActionPerformed(evt);
            }
        });
        jMenu_principal.add(menu_cuenta);

        menu_cuenta2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_cuenta2.setText("Realizar Backup");
        menu_cuenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cuenta2ActionPerformed(evt);
            }
        });
        jMenu_principal.add(menu_cuenta2);

        menu_cuenta3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_cuenta3.setText("Salir");
        menu_cuenta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cuenta3ActionPerformed(evt);
            }
        });
        jMenu_principal.add(menu_cuenta3);

        jMenuBar1.add(jMenu_principal);

        jMenu_buscar.setText("buscar");
        jMenu_buscar.setFocusable(false);
        jMenu_buscar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        bscUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bscUsuario.setText("Usuario");
        bscUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscUsuarioActionPerformed(evt);
            }
        });
        jMenu_buscar.add(bscUsuario);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu_buscar.add(jMenuItem3);

        bscPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bscPrestamo.setText("Prestamo");
        bscPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscPrestamoActionPerformed(evt);
            }
        });
        jMenu_buscar.add(bscPrestamo);

        bscTPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bscTPrestamo.setText("Tipo de Prestamo");
        bscTPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscTPrestamoActionPerformed(evt);
            }
        });
        jMenu_buscar.add(bscTPrestamo);

        bscRuta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bscRuta.setText("Ruta");
        bscRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscRutaActionPerformed(evt);
            }
        });
        jMenu_buscar.add(bscRuta);

        bscRuta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bscRuta1.setText("Abonaciones");
        bscRuta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscRuta1ActionPerformed(evt);
            }
        });
        jMenu_buscar.add(bscRuta1);

        bscRuta2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bscRuta2.setText("Gastos");
        bscRuta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscRuta2ActionPerformed(evt);
            }
        });
        jMenu_buscar.add(bscRuta2);

        jMenuBar1.add(jMenu_buscar);

        jMenu_nuevo.setText("nuevo");
        jMenu_nuevo.setFocusable(false);
        jMenu_nuevo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        insUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insUsuario.setText("Usuario");
        insUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insUsuarioActionPerformed(evt);
            }
        });
        jMenu_nuevo.add(insUsuario);

        insPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insPrestamo.setText("Prestamo");
        insPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insPrestamoActionPerformed(evt);
            }
        });
        jMenu_nuevo.add(insPrestamo);

        insRuta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insRuta.setText("Ruta");
        insRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insRutaActionPerformed(evt);
            }
        });
        jMenu_nuevo.add(insRuta);

        insRuta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insRuta1.setText("Cliente");
        insRuta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insRuta1ActionPerformed(evt);
            }
        });
        jMenu_nuevo.add(insRuta1);

        insTPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insTPrestamo.setText("Tipo de Prestamo");
        insTPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insTPrestamoActionPerformed(evt);
            }
        });
        jMenu_nuevo.add(insTPrestamo);

        insPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insPago.setText("Pago");
        insPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insPagoActionPerformed(evt);
            }
        });
        jMenu_nuevo.add(insPago);
        jMenu_nuevo.add(jSeparator1);

        insAbono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insAbono.setText("Abono");
        insAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insAbonoActionPerformed(evt);
            }
        });
        jMenu_nuevo.add(insAbono);

        insPago1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insPago1.setText("Gasto");
        insPago1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insPago1ActionPerformed(evt);
            }
        });
        jMenu_nuevo.add(insPago1);

        jMenuBar1.add(jMenu_nuevo);
        jMenu_nuevo.getAccessibleContext().setAccessibleName("nuevo ");

        jMenu_config1.setText("reportes");
        jMenu_config1.setFocusable(false);
        jMenu_config1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jMenu_config1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu_config1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_config1MouseClicked(evt);
            }
        });
        jMenu_config1.add(jSeparator4);

        showReportPrestamosActivos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showReportPrestamosActivos.setText("Prestamos Activos");
        showReportPrestamosActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReportPrestamosActivosActionPerformed(evt);
            }
        });
        jMenu_config1.add(showReportPrestamosActivos);

        showReportPrestamosActivos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showReportPrestamosActivos1.setText("Estado de Resultados");
        showReportPrestamosActivos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReportPrestamosActivos1ActionPerformed(evt);
            }
        });
        jMenu_config1.add(showReportPrestamosActivos1);

        showReportPrestamosActivos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showReportPrestamosActivos2.setText("Cobros");
        showReportPrestamosActivos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReportPrestamosActivos2ActionPerformed(evt);
            }
        });
        jMenu_config1.add(showReportPrestamosActivos2);

        showReportPrestamosActivos3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showReportPrestamosActivos3.setText("Ganancias");
        showReportPrestamosActivos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReportPrestamosActivos3ActionPerformed(evt);
            }
        });
        jMenu_config1.add(showReportPrestamosActivos3);

        jMenuBar1.add(jMenu_config1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(650, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(585, 585, 585))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cuentaActionPerformed
        // TODO add your handling code here:
       frm_consult_cuenta frm = new frm_consult_cuenta(this, true);
       frm.setVisible(true);
    }//GEN-LAST:event_menu_cuentaActionPerformed

    private void insUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insUsuarioActionPerformed
        // TODO add your handling code here:
        frm_insert_user frm = new frm_insert_user(this, true);
        frm.setVisible(true);
        
    }//GEN-LAST:event_insUsuarioActionPerformed

    private void insPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insPrestamoActionPerformed
        // TODO add your handling code here:
        frm_insert_prestamo frm_prestamo = new frm_insert_prestamo(this,true);
        frm_prestamo.setVisible(true);
        
    }//GEN-LAST:event_insPrestamoActionPerformed

    private void insRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insRutaActionPerformed
        // TODO add your handling code here:
        frm_insert_ruta frm_ruta = new frm_insert_ruta(this,true);
        frm_ruta.setVisible(true);
    }//GEN-LAST:event_insRutaActionPerformed

    private void insTPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insTPrestamoActionPerformed
        // TODO add your handling code here:
        frm_insert_tprestamo frm_tprestamo = new frm_insert_tprestamo(this, true);
        frm_tprestamo.setVisible(true);
    }//GEN-LAST:event_insTPrestamoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frm_consult_client frm_cons_client = new frm_consult_client(this, true);
        frm_cons_client.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void bscUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscUsuarioActionPerformed
        // TODO add your handling code here:
        frm_consult_user frm = new frm_consult_user(this,true);
        frm.setVisible(true);
    }//GEN-LAST:event_bscUsuarioActionPerformed

    private void bscPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscPrestamoActionPerformed
        // TODO add your handling code here:
        frm_consult_prestamo frm = new frm_consult_prestamo(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_bscPrestamoActionPerformed

    private void bscTPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscTPrestamoActionPerformed
        // TODO add your handling code here:
        frm_consult_tprestamo frm = new frm_consult_tprestamo(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_bscTPrestamoActionPerformed

    private void bscRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscRutaActionPerformed
        // TODO add your handling code here:
        frm_consult_ruta frm = new frm_consult_ruta(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_bscRutaActionPerformed

    private void insPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insPagoActionPerformed
        // TODO add your handling code here:
        frm_eleccion_pago frm = new frm_eleccion_pago(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_insPagoActionPerformed

    private void insRuta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insRuta1ActionPerformed
        // TODO add your handling code here:
        frm_insert_client frm_client = new frm_insert_client(this,true);
        frm_client.setVisible(true);
    }//GEN-LAST:event_insRuta1ActionPerformed

    private void insAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insAbonoActionPerformed
        // TODO add your handling code here:
        frm_insert_abono frm = new frm_insert_abono(this, true);
        frm.setVisible(true);
        
    }//GEN-LAST:event_insAbonoActionPerformed

    private void bscRuta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscRuta1ActionPerformed
        // TODO add your handling code here:
        frm_consult_abono frm  = new frm_consult_abono(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_bscRuta1ActionPerformed

    private void jMenu_config1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_config1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_config1MouseClicked

    private void jMenu_config1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_config1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_config1MousePressed

    private void showReportPrestamosActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReportPrestamosActivosActionPerformed
        // TODO add your handling code here:
        PrestActRunnable runnable=new PrestActRunnable(); 
        Thread hilo = new Thread(runnable);
        hilo.start();
    }//GEN-LAST:event_showReportPrestamosActivosActionPerformed

    private void insPago1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insPago1ActionPerformed
        // TODO add your handling code here:
        frm_insert_gastos frm = new frm_insert_gastos(this);
        frm.setVisible(true);
    }//GEN-LAST:event_insPago1ActionPerformed

    private void bscRuta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscRuta2ActionPerformed
        // TODO add your handling code here:
        frm_consult_gasto frm = new frm_consult_gasto(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_bscRuta2ActionPerformed

    private void showReportPrestamosActivos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReportPrestamosActivos1ActionPerformed
        // TODO add your handling code here:
        frm_rep_eResultado frm;
        try {
            frm = new frm_rep_eResultado(this,true);
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_showReportPrestamosActivos1ActionPerformed

    private void menu_cuenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cuenta2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fChooser = new JFileChooser();
        fChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fChooser.showSaveDialog(new Frame());
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                File createdFile = fChooser.getSelectedFile();
                Backup.pg_dump("postgres", 
                        "localhost",
                        "AyMDB",
                        "\""+createdFile.getAbsolutePath()
                                +File.separator+"AyM "
                                +Utilities.getCurrentDate().toString()
                                +".backup"+"\"");
                Mensajes.confirmar(evt,"BACKUP REALIZADO EXITOSAMENTE");
            } catch (IOException ex) {
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                Mensajes.mensajeError(evt, "Error de Lectura");
            }
        }
        
    }//GEN-LAST:event_menu_cuenta2ActionPerformed

    private void showReportPrestamosActivos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReportPrestamosActivos2ActionPerformed
        // TODO add your handling code here:
        frm_rep_cobros frm = new frm_rep_cobros(this);
        frm.setVisible(true);
    }//GEN-LAST:event_showReportPrestamosActivos2ActionPerformed

    private void showReportPrestamosActivos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReportPrestamosActivos3ActionPerformed
        // TODO add your handling code here:
        frm_consult_ganancia frm = new frm_consult_ganancia(this,true);
        frm.setVisible(true);
    }//GEN-LAST:event_showReportPrestamosActivos3ActionPerformed

    private void menu_cuenta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cuenta3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menu_cuenta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                principal frm = new principal();
                frm.setExtendedState(MAXIMIZED_BOTH);
                frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bscPrestamo;
    private javax.swing.JMenuItem bscRuta;
    private javax.swing.JMenuItem bscRuta1;
    private javax.swing.JMenuItem bscRuta2;
    private javax.swing.JMenuItem bscTPrestamo;
    private javax.swing.JMenuItem bscUsuario;
    private javax.swing.JMenuItem insAbono;
    private javax.swing.JMenuItem insPago;
    private javax.swing.JMenuItem insPago1;
    private javax.swing.JMenuItem insPrestamo;
    private javax.swing.JMenuItem insRuta;
    private javax.swing.JMenuItem insRuta1;
    private javax.swing.JMenuItem insTPrestamo;
    private javax.swing.JMenuItem insUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jMenu_buscar;
    private javax.swing.JMenu jMenu_config1;
    private javax.swing.JMenu jMenu_nuevo;
    private javax.swing.JMenu jMenu_principal;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem menu_cuenta;
    private javax.swing.JMenuItem menu_cuenta2;
    private javax.swing.JMenuItem menu_cuenta3;
    private javax.swing.JMenuItem showReportPrestamosActivos;
    private javax.swing.JMenuItem showReportPrestamosActivos1;
    private javax.swing.JMenuItem showReportPrestamosActivos2;
    private javax.swing.JMenuItem showReportPrestamosActivos3;
    // End of variables declaration//GEN-END:variables
}
